name = "example_library"

[library]
source-dir="src"

[preprocess]
[preprocess.cpp]

[dependencies]
atomstruc = { git = "https://github.com/nedtaylor/atomstruc", branch = "column-major-order" }
diffstruc = { git = "https://github.com/nedtaylor/diffstruc", tag = "v1.2.0" }
graphstruc = { git = "https://github.com/nedtaylor/graphstruc", tag = "v0.2.1" }
