name: Bug report
about: Something is not working
description: A clear and concise description of what the bug is.
title: "[BUG]"
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        A clear and concise description of what the bug is and what the expected behaviour is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? If possible, please provide a minimal reproducible example."
      placeholder: |
        Does the library compile? Is there an issue with a unit test or example? Or is the bug encountered when calling the library? If possible, provide a step-by-step guide:
        1.
        2.
        3.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version number
      description: "What was the latest version (or branch) of athena is the bug reproducible in?"
      placeholder: 1.3.3
    validations:
      required: true
  - type: input
    id: compiler
    attributes:
      label: Fortran compiler
      description: "What Fortran compiler (and version) was used?"
      placeholder: gfortran version 14.0
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform and Architecture
      description: "What architecture and operating system was the bug encountered on?"
      placeholder: macOS/ARM 10.14
    validations:
      required: true
  - type: checkboxes
    id: build
    attributes:
      label: Build method
      description: "What build methods was this issue encountered with?"
      options:
        - label: fpm
        - label: cmake
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      placeholder: Any further relevant context, i.e. screenshots, links to other issues, version number of build method.
    validations:
      required: false
