NAME := wandb_network_sine
MAIN := main.F90
REQUIRED_MODS := athena_wandb
CPP_MACROS := _WANDB
SETUP_ENV_SCRIPT := ../../tools/setup_wf_env.sh
RUN_ENV := WANDB_MODE=offline WANDB_SILENT=true

include ../common.mk
