name: run-fpm-examples

on:
  push:
    branches:
      - main
      - development
      - 'releases/**'
    paths:
      - ".github/workflows/fpm_examples.yml"
      - "fpm.toml"
      - "**.f90"
  pull_request:
    paths:
      - ".github/workflows/fpm_examples.yml"
      - "fpm.toml"
      - "**.f90"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: fpm
  cancel-in-progress: false

jobs:
  build-and-test-fpm-debug:
    name: Run examples in debug mode
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
        - {compiler: gcc, version: 15}
        - {compiler: intel, version: '2025.2'}
        # - {compiler: lfortran, version: '0.45.0'}
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    # ----------------------------------------------------
    # Conda path (GCC)
    # ----------------------------------------------------
    - name: Setup conda (for gfortran)
      if: matrix.toolchain.compiler == 'gcc'
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.11

    - name: Install gfortran via conda
      if: matrix.toolchain.compiler == 'gcc'
      shell: bash -l {0}
      run: |
        conda install -y -c conda-forge "gfortran=${{ matrix.toolchain.version }}"
        echo "FC=$(which gfortran)" >> $GITHUB_ENV

    # ----------------------------------------------------
    # Non-conda compilers (future-proof)
    # ----------------------------------------------------
    - if: ${{ !(matrix.toolchain.compiler == 'gcc') }}
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - uses: fortran-lang/setup-fpm@v7
      id: setup-fpm
      with:
        fpm-version: "v0.13.0"

    - name: Download MNIST dataset
      run: |
        echo "Leaving athena directory"
        pwd
        cd ..
        git clone https://github.com/halimb/MNIST-txt.git
        cd MNIST-txt
        unzip MNIST_txt.zip
        cd ../athena
        echo "Returning to athena directory"
        find example/mnist*/test_job.in -type f -exec sed -i 's|dataset_dir = "../../DMNIST"|dataset_dir = "../MNIST-txt"|' {} \;

    - name: Run examples
      shell: bash -l {0}
      run: |
        ${{ env.FC }} --version
        fpm run --example mnist --profile debug --compiler ${{ env.FC }}
